### PR TITLE
feat: Add support for 64 bit stable memory

### PR DESCRIPTION
**Pull request by dsarlis**
This patch adds support for the new 64 bit stable memory implementation. It's bare bones in the sense that it only provides the wrappers around the low level system api but should be enough for devs to start using the new api.

### CODE REVIEW

**Review by krpeacock — APPROVED** [review]

**Comment by dsarlis** [comment]
Thanks for the review @krpeacock! What's the process to get a new release that will include this? Does it happen weekly or on an ad-hoc basis?

**Comment by krpeacock** [comment]
Biweekly, generally

**Comment by dsarlis** [comment]
> Biweekly, generally

@krpeacock Cool! Is it going to be this week or next? I'd like to understand the timeline so I can inform downstream users who are expecting this feature to be available.

**Comment by krpeacock** [comment]
@dsarlis we will try to do one this week

**Pull request merged**
