### PR TITLE
docs: Add DRAFT doc for Rust support to the cdk-rs repo (intro, hello tutorial)

### PR DESCRIPTION
**Pull request by lsgunnlsgunn**
I have move my DRAFT documentation for Rust support to this repo to be included in the SDK doc site.

### CODE REVIEW

**Comment by lsgunnlsgunn** [comment]
I'd also like to addd BigMap in the context of a tutorial to this section.

**Comment by hansl** [comment]
Let's chat on Monday about this PR. I like it, but I'd like to see a few things, for example re-using the actual examples from this repo as the documentation instead of creating new files that are just copies.

**Comment by lsgunnlsgunn** [comment]
I have an idea about how to make the profile tutorial more useful/meaningful, so I'm converting this to a DRAFT PR.

**Comment by lsgunnlsgunn** [comment]
Hiding content about profile_inter_rs and adding a section about identity and extending this sample to create a LinkedUp example..

**Comment by lsgunnlsgunn** [comment]
Took care of this in a different PR so closing this as obsolete now.

**Pull request closed without merging**
