### PR TITLE
fix: Update http_request transform type.

### PR DESCRIPTION
**Pull request by qj-yu**
# Description

There was a change on the replica side which updates `canister_http` `transform` function type to align with original design in spec.   This PR makes a consistent update as replica, to be in sync with spec.

# How Has This Been Tested?

* Testing `canister_http_request` call using rust canister built with this updated CDK, and updated replica.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] I have made corresponding changes to the documentation. (There is no documentation update, since this change is to align with documentation.)

### CODE REVIEW

**Comment by lwshang** [comment]
Thanks @qj-yu!
Could you also update the example test at: https://github.com/dfinity/cdk-rs/blob/main/examples/management_canister/src/caller/lib.rs#L76

**Comment by qj-yu** [comment]
> Thanks @qj-yu! Could you also update the example test at: https://github.com/dfinity/cdk-rs/blob/main/examples/management_canister/src/caller/lib.rs#L76

@lwshang The `http_request` related tests (management_canister tests and cycles charge tests) are fixed.  Could you take a look?

**Comment by qj-yu** [comment]
> @qj-yu Examples CI of this repo is still running with dfx v0.11.1 which isn't bundled with new replica that contains recent canister http request changes. I'm working on updating dfx for CI and will merge this PR after then.

Thanks @lwshang ! The replica change is expected to be built into a release binary in the next couple of days.   What do you need for including the new replica build to `dfx`?

**Comment by lwshang** [comment]
That may take a while to happen with following steps:
1. feature/fix MR of replica gets merged
2. replica cut a release
3. IC proposal for updating replica got approved (mainnet then run with new replica)
4. sdk team update the dfx bundled replica
5. sdk team cut a new release of dfx with new replica
After step 2, I may be able to test locally.
When we reach step 5, I will update CI of this repo and merge this PR.

**Review by lwshang — APPROVED** [review]

**Pull request merged**
