### PR TITLE
feat: CallFutureRaw - call commit point clarification

### PR DESCRIPTION
**Pull request by levifeldman**
# Summary
Some system-api calls can only be called within a callback. This feature lets the canister know if the code following the call_future.await is in a callback/separate-execution-message or in the same execution-message.
This feature adds the `CallFutureRaw` type for the return type of the `call_raw` and `call_raw128` functions.
By checking the `call_perform_status_code` field or the `will_perform()` method on the `CallFuture` struct, the canister can know if the code following the .await is within a callback or not.

This can also be done for the `call`, `call_with_payment`, and `call_with_payment128` functions by wrapping the `CallFuture` in a `CallFutureCandid`.

# Test

The test is in the e2e tests in the api-call canister test.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by levifeldman** [comment]
Hey @lwshang , @roman-kashitsyn , @adamspofford-dfinity , 
What do you guys think of this? 
and do you know of a way to make the test better?

**Comment by adamspofford-dfinity** [comment]
What additional functionality does this enable for the caller that they would not get with `futures::poll!(call_future)`?

**Comment by levifeldman** [comment]
Hey @adamspofford-dfinity, The `futures::poll!(call_future)` macro takes ownership of the call_future so it doesn't work to call .await on the call_future after a poll!(call_future) . here is a sample:

```rust
#[update]
pub async fn test_call_future_raw() {
    let callfutureraw = call_raw128(
        Principal::from_slice(&[]),
        "t",
        &[1,2,3],
        0
    );
    let first_poll: Poll<CallResult<Vec<u8>>> = futures::poll!(callfutureraw);
    if let Poll::Pending = first_poll {
        callfutureraw.await;
        msg_cycles_refunded128();
    }
}

```

This code fails to compile with the following error:
<pre><font color="#F66151"><b>error[E0382]</b></font><b>: use of moved value: `callfutureraw`</b>
   <font color="#2A7BDE"><b>--&gt; </b></font>src/lib.rs:132:9
    <font color="#2A7BDE"><b>|</b></font>
<font color="#2A7BDE"><b>124</b></font> <font color="#2A7BDE"><b>| </b></font>    let callfutureraw = call_raw128(
    <font color="#2A7BDE"><b>| </b></font>        <font color="#2A7BDE"><b>-------------</b></font> <font color="#2A7BDE"><b>move occurs because `callfutureraw` has type `impl futures::Future&lt;Output = Result&lt;std::vec::Vec&lt;u8&gt;, (RejectionCode, std::string::String)&gt;&gt;`, which does not implement the `Copy` trait</b></font>
<font color="#2A7BDE"><b>...</b></font>
<font color="#2A7BDE"><b>130</b></font> <font color="#2A7BDE"><b>| </b></font>    let first_poll: Poll&lt;CallResult&lt;Vec&lt;u8&gt;&gt;&gt; = futures::poll!(callfutureraw);
    <font color="#2A7BDE"><b>| </b></font>                                                               <font color="#2A7BDE"><b>-------------</b></font> <font color="#2A7BDE"><b>value moved here</b></font>
<font color="#2A7BDE"><b>131</b></font> <font color="#2A7BDE"><b>| </b></font>    if let Poll::Pending = first_poll {
<font color="#2A7BDE"><b>132</b></font> <font color="#2A7BDE"><b>| </b></font>        callfutureraw.await;
    <font color="#2A7BDE"><b>| </b></font>        <font color="#F66151"><b>^^^^^^^^^^^^^</b></font> <font color="#F66151"><b>value used here after move</b></font>
</pre>

**Comment by levifeldman** [comment]
Hey @adamspofford-dfinity , thank you, `futures::poll!(call_future)` gets it done.

**Pull request closed without merging**
